### ISSUE TITLE
Inresolved variable

### ISSUE THREAD

**Issue by idanbuller** [sblosser/pyshadowcopy#3]
def __vss_create(self, drive_letter):
        sc = self.wmi.get("Win32_ShadowCopy")
        createparams = sc.Methods_("Create").InParameters.SpawnInstance_()
        createparams.Properties_[1].value = "{0}:\\".format(drive_letter)
        results = wmi.ExecMethod_("Create", createparams)
        return results.Properties_[1].value

# The wmi variable needs to be part of the class (line 79)

needs to be fixed to - 
    def __vss_create(self, drive_letter):
        sc = self.wmi.get("Win32_ShadowCopy")
        createparams = sc.Methods_("Create").InParameters.SpawnInstance_()
        createparams.Properties_[1].value = "{0}:\\".format(drive_letter)
        results = self.wmi.ExecMethod_("Create", createparams)
        return results.Properties_[1].value

**Comment by sblosser** [comment]
Feel free to fork and resolve this issue yourself. This project is no longer actively maintained. Thanks!
